const KEY='milk-record-v1';
const MAX_FILL_HEIGHT=74;
const DEFAULT_VISCOSITY=10;
const today=()=>new Date().toISOString().slice(0,10);
const initial={dose:3,color:'#dfd1b9',current:{id:Date.now(),start:today(),amount:0},bottles:[],logs:{}};
let state=(()=>{try{return {...initial,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return initial}})();
delete state.viscosity;
let busy=false, calendarDate=new Date();
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const bottleLine='<svg class="bottle-line" viewBox="0 0 234 364" preserveAspectRatio="none" aria-hidden="true"><path d="M70 3 H164 V27 C164 43 170 50 190 55 C211 61 220 76 220 99 V348 Q220 361 207 361 H27 Q14 361 14 348 V99 C14 76 23 61 44 55 C64 50 70 43 70 27 Z"/></svg>';
function ensureBottleLines(){ $$('.jar,.mini-jar').forEach(jar=>{if(!jar.querySelector('.bottle-line'))jar.insertAdjacentHTML('beforeend',bottleLine)}) }
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function fmt(d){return new Intl.DateTimeFormat('ja-JP',{month:'short',day:'numeric'}).format(new Date(d+'T00:00:00'))}
function showFullMessage(){const message=$('#fullMessage');message.classList.add('show');clearTimeout(window.fullMessageTimer);window.fullMessageTimer=setTimeout(()=>message.classList.remove('show'),4500)}
function askPour(number){return new Promise(resolve=>{const dialog=$('#pourConfirm'),approve=$('#approvePour'),cancel=$('#cancelPour');$('#confirmQuestion').textContent=`本日${number}回目のミルクを注ぎますか？`;const finish=value=>{dialog.close();resolve(value)};approve.onclick=()=>finish(true);cancel.onclick=()=>finish(false);dialog.oncancel=e=>{e.preventDefault();finish(false)};dialog.showModal()})}
function positionStream(fillPercent){const stage=$('.stage'),jar=$('#currentJar');if(!stage||!jar)return;const stageRect=stage.getBoundingClientRect(),jarRect=jar.getBoundingClientRect(),streamTop=68,innerBottom=jarRect.bottom-stageRect.top-jarRect.height*.02,liquidHeight=jarRect.height*fillPercent/100;stage.style.setProperty('--stream-length',`${Math.max(20,innerBottom-liquidHeight-streamTop)}px`)}
function update(){
 document.documentElement.style.setProperty('--milk',state.color); $('#milkColor').value=state.color;
 const fillPercent=Math.min(MAX_FILL_HEIGHT,state.current.amount/1000*MAX_FILL_HEIGHT);$('#milk').style.height=`${fillPercent}%`;positionStream(fillPercent);$('#jarDate').textContent=fmt(state.current.start)+' ～'; $('#jarAmount').textContent=`${state.current.amount.toLocaleString()} / 1,000 ml`;
 const log=state.logs[today()]||{count:0,amount:0}; $('#dailyCount').textContent=log.count; $('#dailyAmount').textContent=log.amount; $('#pourStatus').textContent=state.dose+' ml';
 $$('.dose-switch button').forEach(b=>b.classList.toggle('active',+b.dataset.dose===state.dose)); renderShelf(); ensureBottleLines(); renderCalendar(); save();
}
async function pour(){if(busy)return;const todayLog=state.logs[today()]||{count:0};if(todayLog.count>0&&!await askPour(todayLog.count+1))return;busy=true;const btn=$('#pourBtn'), duration=700+DEFAULT_VISCOSITY*110;btn.disabled=true;$('#recordView').classList.add('pouring');$('#pourStatus').textContent='注いでいます…';
 setTimeout(()=>{const d=today(),amount=Math.min(state.dose,1000-state.current.amount);state.current.amount+=amount;state.logs[d]??={count:0,amount:0};state.logs[d].count++;state.logs[d].amount+=amount;$('#recordView').classList.remove('pouring');update();
 if(state.current.amount>=1000){state.current.end=d;state.bottles.unshift(state.current);state.current={id:Date.now(),start:d,amount:0};update();showFullMessage()}
 $('#pourStatus').textContent=state.dose+' ml';setTimeout(()=>{busy=false;btn.disabled=false},300)},duration);
}
function renderCalendar(){const y=calendarDate.getFullYear(),m=calendarDate.getMonth();$('#monthTitle').textContent=`${y}年 ${m+1}月`;const first=new Date(y,m,1).getDay(),last=new Date(y,m+1,0).getDate();let html='';for(let i=0;i<first;i++)html+='<div class="day empty"></div>';for(let d=1;d<=last;d++){const key=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,l=state.logs[key];html+=`<div class="day ${key===today()?'today':''}"><b>${d}</b>${l?`<div class="dot">${l.count}回 · ${l.amount}ml</div>`:''}</div>`}$('#calendar').innerHTML=html}
function bottleMarkup(b){const range=`${fmt(b.start)} ～ ${fmt(b.end)}`,fill=b.amount/1000*MAX_FILL_HEIGHT;return `<article class="shelf-item"><div class="stored-bottle"><div class="cork" aria-hidden="true"></div><div class="mini-jar"><div class="mini-milk" style="height:${fill}%"></div><div class="shelf-label"><small>MILK</small><b>${range}</b><span>1 L</span></div></div></div><button type="button" data-bottle="${b.id}">手に取る</button></article>`}
function renderShelf(){$('#shelf').innerHTML=state.bottles.length?state.bottles.map(b=>bottleMarkup(b)).join(''):'<p>満杯になった瓶が、ここに並びます。</p>';$$('[data-bottle]').forEach(button=>button.onclick=()=>{const bottle=state.bottles.find(x=>String(x.id)===button.dataset.bottle);if(bottle)inspect(bottle)})}
function inspect(b=state.current){const ageDays=b.end?Math.max(0,(Date.now()-new Date(`${b.end}T00:00:00`).getTime())/86400000):0,viscosity=b.end?Math.min(40,DEFAULT_VISCOSITY+ageDays/365*30):DEFAULT_VISCOSITY;$('#inspectTitle').textContent=b.end?`${fmt(b.start)} ～ ${fmt(b.end)}`:`${fmt(b.start)} ～`;const jar=$('#physicsJar');jar.dataset.level=Math.min(MAX_FILL_HEIGHT,b.amount/1000*MAX_FILL_HEIGHT);jar.dataset.viscosity=viscosity;$('#inspect').showModal();initSurfaceFluid()}
function initPhysics(){
 const jar=$('#physicsJar');jar.querySelector('.mini-milk').style.display='none';let canvas=jar.querySelector('canvas');if(!canvas){canvas=document.createElement('canvas');canvas.width=234;canvas.height=364;jar.prepend(canvas)}
 const ctx=canvas.getContext('2d'),level=+jar.dataset.level||0;let x=0,y=0,rot=0,targetRot=0,drag=false,px=0,py=0,vx=0,energy=0,phase=0,raf;
 const hex=state.color.replace('#',''),rgb=[parseInt(hex.slice(0,2),16),parseInt(hex.slice(2,4),16),parseInt(hex.slice(4,6),16)];
 function draw(){phase+=.12;energy*=.965;rot+=(targetRot-rot)*.11;jar.style.transform=`translate(${x}px,${y}px) rotate(${rot}deg)`;ctx.clearRect(0,0,234,364);if(level>0){const base=364-(level/100)*340,slope=Math.tan(-rot*Math.PI/180),amp=Math.min(22,energy);ctx.beginPath();for(let px=0;px<=234;px+=3){const edge=(px-117)*slope;const wave=Math.sin(px*.055+phase)*amp+Math.sin(px*.12-phase*1.7)*amp*.32;const py=Math.max(8,Math.min(358,base+edge+wave));px?ctx.lineTo(px,py):ctx.moveTo(px,py)}ctx.lineTo(234,364);ctx.lineTo(0,364);ctx.closePath();const g=ctx.createLinearGradient(0,base,0,364);g.addColorStop(0,`rgba(${Math.min(255,rgb[0]+18)},${Math.min(255,rgb[1]+18)},${Math.min(255,rgb[2]+18)},.96)`);g.addColorStop(.18,`rgb(${rgb.join(',')})`);g.addColorStop(1,`rgb(${Math.max(0,rgb[0]-13)},${Math.max(0,rgb[1]-13)},${Math.max(0,rgb[2]-13)})`);ctx.fillStyle=g;ctx.fill();ctx.strokeStyle='rgba(255,255,255,.75)';ctx.lineWidth=3;ctx.stroke();for(let i=0;i<5;i++){const bx=(i*43+phase*9)%210+12,by=base+34+(i*47)%Math.max(55,350-base);ctx.beginPath();ctx.arc(bx,by,1.5+(i%3),0,Math.PI*2);ctx.fillStyle='rgba(255,255,255,.28)';ctx.fill()}}raf=requestAnimationFrame(draw)}
 jar.onpointerdown=e=>{drag=true;px=e.clientX;py=e.clientY;jar.setPointerCapture(e.pointerId)};jar.onpointermove=e=>{if(!drag)return;vx=e.clientX-px;const vy=e.clientY-py;x=Math.max(-120,Math.min(120,x+vx));y=Math.max(-65,Math.min(65,y+vy));targetRot=Math.max(-72,Math.min(72,targetRot+vx*.3));energy=Math.min(20,energy+Math.abs(vx)*.8+Math.abs(vy)*.25);px=e.clientX;py=e.clientY};jar.onpointerup=()=>{drag=false;if(window.Matter){const body=Matter.Bodies.rectangle(x,y,125,190);Matter.Body.setAngularVelocity(body,vx*.001);targetRot=Matter.Common.clamp(targetRot+body.angularVelocity*20,-72,72)}};
 const tilt=n=>{targetRot=Math.max(-72,Math.min(72,targetRot+n));energy=Math.min(18,energy+8)};$('#tiltLeft').onclick=()=>tilt(-18);$('#tiltRight').onclick=()=>tilt(18);$('#shake').onclick=()=>{energy=22;jar.animate([{transform:`translate(${x-22}px,${y}px) rotate(${rot-7}deg)`},{transform:`translate(${x+22}px,${y}px) rotate(${rot+7}deg)`}],{duration:140,iterations:5,direction:'alternate'})};cancelAnimationFrame(window.milkRaf);draw();window.milkRaf=raf;
}
function initParticleFluid(){
 const jar=$('#physicsJar');jar.querySelector('.mini-milk').style.display='none';let canvas=jar.querySelector('canvas');if(!canvas){canvas=document.createElement('canvas');canvas.width=234;canvas.height=364;jar.prepend(canvas)}
 cancelAnimationFrame(window.milkRaf);const ctx=canvas.getContext('2d'),level=+jar.dataset.level||0,visc=+jar.dataset.viscosity||DEFAULT_VISCOSITY;let x=0,y=0,angle=0,target=0,drag=false,px=0,py=0,lastVX=0,lastVY=0;
 const hex=state.color.replace('#',''),rgb=[parseInt(hex.slice(0,2),16),parseInt(hex.slice(2,4),16),parseInt(hex.slice(4,6),16)],particles=[],count=Math.round(level*1.25),radius=13;
 for(let i=0;i<count;i++){const col=i%10,row=Math.floor(i/10);particles.push({x:27+col*20+(row%2)*5,y:340-row*17,vx:0,vy:0})}
 function impulse(ix,iy){particles.forEach((p,i)=>{p.vx+=ix*(.65+(i%7)/20);p.vy+=iy*(.72+(i%5)/18)})}
 function frame(){angle+=(target-angle)*.12;jar.style.transform=`translate(${x}px,${y}px) rotate(${angle}deg)`;const a=angle*Math.PI/180,gx=Math.sin(a)*.34,gy=Math.cos(a)*.34,damping=.986-visc*.004,cohesion=.0015+visc*.00055;
  for(let step=0;step<2;step++){for(const p of particles){p.vx+=gx;p.vy+=gy;p.vx*=damping;p.vy*=damping;const cx=117-p.x,cy=290-p.y;p.vx+=cx*cohesion;p.vy+=cy*cohesion*.12;p.x+=p.vx;p.y+=p.vy;if(p.x<radius){p.x=radius;p.vx=Math.abs(p.vx)*.38}if(p.x>234-radius){p.x=234-radius;p.vx=-Math.abs(p.vx)*.38}if(p.y<radius){p.y=radius;p.vy=Math.abs(p.vy)*.3}if(p.y>364-radius){p.y=364-radius;p.vy=-Math.abs(p.vy)*.24}}
   for(let i=0;i<particles.length;i++)for(let j=i+1;j<particles.length;j++){const p=particles[i],q=particles[j],dx=q.x-p.x,dy=q.y-p.y,ds=dx*dx+dy*dy,min=radius*1.55;if(ds>0&&ds<min*min){const d=Math.sqrt(ds),push=(min-d)*.055,nx=dx/d,ny=dy/d;p.vx-=nx*push;p.vy-=ny*push;q.vx+=nx*push;q.vy+=ny*push}}}
  ctx.clearRect(0,0,234,364);ctx.save();ctx.fillStyle=`rgb(${rgb.join(',')})`;ctx.strokeStyle=`rgb(${rgb.join(',')})`;ctx.lineWidth=radius*1.7;ctx.lineCap='round';ctx.lineJoin='round';for(let i=0;i<particles.length;i++){const p=particles[i];for(let j=i+1;j<particles.length;j++){const q=particles[j],dx=q.x-p.x,dy=q.y-p.y;if(dx*dx+dy*dy<(radius*2.35)**2){ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.stroke()}}}for(const p of particles){ctx.beginPath();ctx.arc(p.x,p.y,radius,0,Math.PI*2);ctx.fill()}ctx.restore();window.milkRaf=requestAnimationFrame(frame)}
 jar.onpointerdown=e=>{drag=true;px=e.clientX;py=e.clientY;jar.setPointerCapture(e.pointerId)};jar.onpointermove=e=>{if(!drag)return;lastVX=e.clientX-px;lastVY=e.clientY-py;x=Math.max(-120,Math.min(120,x+lastVX));y=Math.max(-65,Math.min(65,y+lastVY));target=Math.max(-72,Math.min(72,target+lastVX*.3));impulse(-lastVX*.035,-lastVY*.045);px=e.clientX;py=e.clientY};jar.onpointerup=()=>{drag=false;impulse(-lastVX*.16,-lastVY*.2)};
 const tilt=n=>{target=Math.max(-72,Math.min(72,target+n));impulse(-n*.07,-1.4)};$('#tiltLeft').onclick=()=>tilt(-18);$('#tiltRight').onclick=()=>tilt(18);$('#shake').onclick=()=>{impulse(lastVX>0?-7:7,-9);lastVX=lastVX>0?-7:7;jar.animate([{transform:`translate(${x-24}px,${y}px) rotate(${angle-7}deg)`},{transform:`translate(${x+24}px,${y}px) rotate(${angle+7}deg)`}],{duration:130,iterations:5,direction:'alternate'})};frame()
}
function initSurfaceFluid(){
 const jar=$('#physicsJar'),held=$('#heldBottle');jar.querySelector('.mini-milk').style.display='none';let canvas=jar.querySelector('canvas');if(!canvas){canvas=document.createElement('canvas');canvas.width=234;canvas.height=364;jar.prepend(canvas)}cancelAnimationFrame(window.milkRaf);
 const ctx=canvas.getContext('2d'),level=+jar.dataset.level||0,visc=+jar.dataset.viscosity||DEFAULT_VISCOSITY,hex=state.color.replace('#',''),rgb=[parseInt(hex.slice(0,2),16),parseInt(hex.slice(2,4),16),parseInt(hex.slice(4,6),16)];let x=0,y=0,angle=0,targetAngle=0,drag=false,px=0,py=0,lastVX=0,lastVY=0;const nodes=Array.from({length:19},()=>({y:0,v:0})),motionScale=Math.min(1,DEFAULT_VISCOSITY/visc);
 const disturb=(power,center=9)=>nodes.forEach((n,i)=>n.v+=power*motionScale*Math.exp(-Math.pow((i-center)/3.2,2))*(i%2?.85:1));
 function render(){angle+=(targetAngle-angle)*.13;held.style.transform=`translate(${x}px,${y}px) rotate(${angle}deg)`;const desiredBase=356-level*3.55,slope=Math.tan(-angle*Math.PI/180),spring=.08/(1+Math.max(0,visc-10)*.05),damp=Math.max(.68,.84-Math.max(0,visc-10)*.004),spread=.12/(1+Math.max(0,visc-10)*.04);let base=desiredBase;
  for(let i=0;i<nodes.length;i++){const target=(i-9)*13*slope,n=nodes[i];n.v+=(target-n.y)*spring;n.v*=damp}for(let i=0;i<nodes.length;i++){const left=i?nodes[i-1].y:2*nodes[0].y-nodes[1].y,right=i<18?nodes[i+1].y:2*nodes[18].y-nodes[17].y;nodes[i].v+=(left+right-2*nodes[i].y)*spread}nodes.forEach(n=>{n.y=Math.max(-420,Math.min(420,n.y+n.v));n.v=Math.max(-24,Math.min(24,n.v))});const mean=nodes.reduce((sum,n)=>sum+n.y,0)/nodes.length;nodes.forEach(n=>n.y-=mean);
  let low=-360,high=360;for(let k=0;k<18;k++){const offset=(low+high)/2,visibleMean=nodes.reduce((sum,n)=>sum+Math.max(5,Math.min(364,desiredBase+n.y+offset)),0)/nodes.length;if(visibleMean<desiredBase)low=offset;else high=offset}base=desiredBase+(low+high)/2;
  ctx.clearRect(0,0,234,364);if(level>0){ctx.beginPath();ctx.moveTo(0,364);ctx.lineTo(0,Math.max(5,Math.min(364,base+nodes[0].y)));for(let i=1;i<nodes.length;i++){const x1=(i-1)*13,y1=Math.max(5,Math.min(364,base+nodes[i-1].y)),x2=i*13,y2=Math.max(5,Math.min(364,base+nodes[i].y)),mx=(x1+x2)/2;ctx.quadraticCurveTo(x1,y1,mx,(y1+y2)/2);if(i===18)ctx.quadraticCurveTo(x2,y2,x2,y2)}ctx.lineTo(234,364);ctx.closePath();ctx.fillStyle=`rgb(${rgb.join(',')})`;ctx.fill();ctx.beginPath();ctx.moveTo(0,Math.max(5,Math.min(364,base+nodes[0].y)));for(let i=1;i<nodes.length;i++){const x1=(i-1)*13,y1=Math.max(5,Math.min(364,base+nodes[i-1].y)),x2=i*13,y2=Math.max(5,Math.min(364,base+nodes[i].y));ctx.quadraticCurveTo(x1,y1,(x1+x2)/2,(y1+y2)/2)}ctx.strokeStyle='rgba(255,255,255,.55)';ctx.lineWidth=2;ctx.stroke()}
  window.milkRaf=requestAnimationFrame(render)}
 function kick(vx,vy){disturb(vy*.5,Math.max(1,Math.min(17,Math.round((117-vx*3)/13))))}
 held.onpointerdown=e=>{drag=true;px=e.clientX;py=e.clientY;held.setPointerCapture(e.pointerId)};held.onpointermove=e=>{if(!drag)return;lastVX=e.clientX-px;lastVY=e.clientY-py;x=Math.max(-120,Math.min(120,x+lastVX));y=Math.max(-65,Math.min(65,y+lastVY));targetAngle=Math.max(-72,Math.min(72,targetAngle+lastVX*.3));kick(lastVX,lastVY);px=e.clientX;py=e.clientY};held.onpointerup=()=>{drag=false;kick(lastVX,lastVY)};
 const tilt=n=>{targetAngle=Math.max(-72,Math.min(72,targetAngle+n));disturb(-n*.12,n>0?5:13);if(window.Matter){const body=Matter.Bodies.rectangle(x,y,125,190);Matter.Body.setAngularVelocity(body,n*.001)}};$('#tiltLeft').onclick=()=>tilt(-18);$('#tiltRight').onclick=()=>tilt(18);$('#shake').onclick=()=>{kick(20,-24,true);held.animate([{transform:`translate(${x-25}px,${y}px) rotate(${angle-8}deg)`},{transform:`translate(${x+25}px,${y}px) rotate(${angle+8}deg)`}],{duration:130,iterations:5,direction:'alternate'})};render()
}
$('#pourBtn').onclick=pour;$$('.dose-switch button').forEach(b=>b.onclick=()=>{if(!busy){state.dose=+b.dataset.dose;update()}});$$('nav button').forEach(b=>b.onclick=()=>{$$('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(x=>x.classList.remove('active'));$('#'+b.dataset.view+'View').classList.add('active')});
$('#settingsBtn').onclick=()=>$('#settings').showModal();$('#milkColor').oninput=e=>{state.color=e.target.value;update()};$('#holdCurrent').onclick=()=>inspect();$('#prevMonth').onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()-1);renderCalendar()};$('#nextMonth').onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()+1);renderCalendar()};
let resetCode='';$('#openReset').onclick=()=>{resetCode=String(1000+crypto.getRandomValues(new Uint16Array(1))[0]%9000);$('#resetNumber').textContent=resetCode;$('#resetInput').value='';$('#resetError').textContent='';$('#settings').close();$('#resetCode').showModal();setTimeout(()=>$('#resetInput').focus(),50)};$('#closeResetCode').onclick=()=>$('#resetCode').close();$('#verifyReset').onclick=()=>{if($('#resetInput').value!==resetCode){$('#resetError').textContent='数字が一致しません。';$('#resetInput').select();return}$('#resetCode').close();$('#resetFinal').showModal()};$('#resetInput').onkeydown=e=>{if(e.key==='Enter')$('#verifyReset').click()};$('#cancelReset').onclick=()=>$('#resetFinal').close();$('#executeReset').onclick=()=>{localStorage.removeItem(KEY);state={dose:3,color:'#dfd1b9',current:{id:Date.now(),start:today(),amount:0},bottles:[],logs:{}};$('#resetFinal').close();update()};
$('#todayLabel').textContent=new Intl.DateTimeFormat('ja-JP',{year:'numeric',month:'long',day:'numeric',weekday:'long'}).format(new Date()).toUpperCase();update();
window.addEventListener('resize',()=>positionStream(Math.min(MAX_FILL_HEIGHT,state.current.amount/1000*MAX_FILL_HEIGHT)));
