import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { DRACOLoader } from 'three/addons/loaders/DRACOLoader.js';

const canvas=document.querySelector('#scene'),viewport=document.querySelector('#viewport');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;renderer.shadowMap.enabled=true;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x161b19);scene.fog=new THREE.FogExp2(0x161b19,.008);
const camera=new THREE.PerspectiveCamera(68,1,.03,3000);camera.rotation.order='YXZ';
scene.add(new THREE.HemisphereLight(0xdce6df,0x353933,2.2));const sun=new THREE.DirectionalLight(0xffffff,2.8);sun.position.set(30,70,25);sun.castShadow=true;scene.add(sun);
const flashlight=new THREE.SpotLight(0xfff1c2,0,100,Math.PI/5,.48,1),flashlightTarget=new THREE.Object3D();flashlight.castShadow=true;flashlight.shadow.mapSize.set(1024,1024);flashlight.shadow.bias=-.0001;flashlight.target=flashlightTarget;scene.add(flashlight,flashlightTarget);let flashlightOn=false;
const grid=new THREE.GridHelper(1000,100,0x3d443f,0x252a27);grid.material.opacity=.22;grid.material.transparent=true;scene.add(grid);
const modelRoot=new THREE.Group();scene.add(modelRoot);const colliders=[];let bounds=new THREE.Box3(),size=new THREE.Vector3(),center=new THREE.Vector3();
const initialPosition=new THREE.Vector3(5.48,2.56,.67),initialFeetY=2.56-.035;
const spawn=new THREE.Vector3(),flySpawn=new THREE.Vector3();let mode='walk',yaw=0,pitch=0,velocityY=0,groundY=initialFeetY,loaded=false,started=false,playerHeight=.035,moveSpeed=.2;const bodyRatio=.34/1.68;const keys=new Set();
const getEye=()=>playerHeight,getRadius=()=>playerHeight*bodyRatio;
const ray=new THREE.Raycaster();const down=new THREE.Vector3(0,-1,0),up=new THREE.Vector3(0,1,0);const clock=new THREE.Clock();
const $=s=>document.querySelector(s),loading=$('#loading'),progress=$('#progress'),percent=$('#percent'),intro=$('#intro'),hint=$('#hint'),modeLabel=$('#modeLabel'),heightLabel=$('#heightLabel'),positionLabel=$('#positionLabel'),statusLabel=$('#statusLabel'),verticalGuide=$('#verticalGuide'),playerHeightInput=$('#playerHeight'),moveSpeedInput=$('#moveSpeed'),flashlightButton=$('#flashlight');
const draco=new DRACOLoader();draco.setDecoderPath('https://cdn.jsdelivr.net/npm/three@0.170.0/examples/jsm/libs/draco/');const loader=new GLTFLoader();loader.setDRACOLoader(draco);
loader.load('assets/gankyu.glb',gltf=>{modelRoot.add(gltf.scene);gltf.scene.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;colliders.push(o);if(o.material){o.material.envMapIntensity=.65}}});bounds.setFromObject(modelRoot);bounds.getSize(size);bounds.getCenter(center);grid.position.y=bounds.min.y-.02;scene.fog.density=1/Math.max(size.length()*2,80);findSpawn();loaded=true;loading.classList.add('done');setTimeout(()=>loading.remove(),600);},xhr=>{if(xhr.total){const p=Math.round(xhr.loaded/xhr.total*100);progress.style.width=p+'%';percent.textContent=p}},()=>{loading.querySelector('p').textContent='モデルを読み込めませんでした';});

function groundAt(pos,maxDrop=Math.max(size.y,20)){ray.set(new THREE.Vector3(pos.x,bounds.max.y+2,pos.z),down);ray.far=size.y+maxDrop+4;const hits=ray.intersectObjects(colliders,false);return hits.length?hits[hits.length-1].point.y:null}
function findSpawn(){flashlight.distance=Math.max(size.length()*.2,2);groundY=initialFeetY;spawn.copy(initialPosition);camera.position.copy(spawn);yaw=0;pitch=0;flySpawn.set(center.x,bounds.max.y+Math.max(size.length()*.35,8),center.z+Math.max(size.z,size.x)*.75);camera.lookAt(center);yaw=camera.rotation.y;pitch=camera.rotation.x}
function requestControl(){if(loaded&&document.pointerLockElement!==canvas)canvas.requestPointerLock()}
function toggleFlashlight(){flashlightOn=!flashlightOn;flashlight.intensity=flashlightOn?150:0;flashlightButton.classList.toggle('active',flashlightOn);flashlightButton.setAttribute('aria-pressed',flashlightOn);flashlightButton.querySelector('b').textContent=flashlightOn?'LIGHT ON':'LIGHT OFF'}
function setMode(next){const eye=getEye();mode=next;velocityY=0;if(mode==='walk'){const y=floorBelow(camera.position,Math.max(size.y,.8));if(y!==null){groundY=y;camera.position.y=y+eye}else camera.position.set(spawn.x,groundY+eye,spawn.z)}document.querySelectorAll('.mode').forEach(b=>{const on=b.dataset.mode===mode;b.classList.toggle('active',on);b.setAttribute('aria-pressed',on)});modeLabel.textContent=mode==='walk'?'WALK':'FREE';verticalGuide.style.opacity=mode==='fly'?'1':'.28'}
function floorBelow(pos,distance){ray.set(pos,down);ray.far=distance+getEye();const h=ray.intersectObjects(colliders,false);return h.length?h[0].point.y:null}
function blocked(direction,distance){const eye=getEye(),origins=[new THREE.Vector3(camera.position.x,camera.position.y-eye+Math.min(.35,eye*.25),camera.position.z),new THREE.Vector3(camera.position.x,camera.position.y-eye*.35,camera.position.z)];for(const origin of origins){ray.set(origin,direction);ray.far=distance;const h=ray.intersectObjects(colliders,false);if(h.length&&h[0].distance<distance)return true}return false}
function moveWalk(delta){const eye=getEye(),bodyRadius=getRadius(),forward=new THREE.Vector3(-Math.sin(yaw),0,-Math.cos(yaw)),right=new THREE.Vector3(Math.cos(yaw),0,-Math.sin(yaw));const wish=new THREE.Vector3();if(keys.has('KeyW'))wish.add(forward);if(keys.has('KeyS'))wish.sub(forward);if(keys.has('KeyD'))wish.add(right);if(keys.has('KeyA'))wish.sub(right);if(wish.lengthSq()){wish.normalize();const step=wish.multiplyScalar(moveSpeed*(keys.has('ShiftLeft')?1.72:1)*delta);if(!blocked(step.clone().normalize(),step.length()+bodyRadius))camera.position.add(step)}const floor=floorBelow(camera.position,Math.max(eye+.65,Math.abs(velocityY*delta)+.2));velocityY-=12*delta;camera.position.y+=velocityY*delta;if(floor!==null&&camera.position.y<=floor+eye+.18&&velocityY<=0){groundY=floor;camera.position.y=groundY+eye;velocityY=0}if(camera.position.y<bounds.min.y-10)resetPosition()}
function moveFly(delta){const f=new THREE.Vector3(0,0,-1).applyEuler(camera.rotation),r=new THREE.Vector3(1,0,0).applyEuler(camera.rotation),wish=new THREE.Vector3();if(keys.has('KeyW'))wish.add(f);if(keys.has('KeyS'))wish.sub(f);if(keys.has('KeyD'))wish.add(r);if(keys.has('KeyA'))wish.sub(r);if(keys.has('Space'))wish.add(up);if(keys.has('ShiftLeft')||keys.has('ShiftRight'))wish.sub(up);if(wish.lengthSq())camera.position.addScaledVector(wish.normalize(),moveSpeed*delta)}
function resetPosition(){if(mode==='walk'){groundY=initialFeetY;camera.position.set(spawn.x,initialFeetY+getEye(),spawn.z);yaw=0;pitch=0}else{camera.position.copy(flySpawn);camera.lookAt(center);yaw=camera.rotation.y;pitch=camera.rotation.x}velocityY=0}
function resize(){const w=viewport.clientWidth,h=viewport.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}
function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.05);if(loaded&&started){mode==='walk'?moveWalk(dt):moveFly(dt);camera.rotation.set(pitch,yaw,0);heightLabel.textContent=((camera.position.y-bounds.min.y)).toFixed(1)+' M';positionLabel.textContent=`${camera.position.x.toFixed(2)} · ${camera.position.y.toFixed(2)} · ${camera.position.z.toFixed(2)}`}flashlight.position.copy(camera.position);flashlightTarget.position.copy(camera.position).add(new THREE.Vector3(0,0,-1).applyQuaternion(camera.quaternion));renderer.render(scene,camera)}
window.addEventListener('resize',resize);window.addEventListener('keydown',e=>{keys.add(e.code);if(['Space','ArrowUp','ArrowDown'].includes(e.code))e.preventDefault();if(e.code==='KeyF')setMode(mode==='walk'?'fly':'walk');if(e.code==='KeyL'&&!e.repeat)toggleFlashlight()});window.addEventListener('keyup',e=>keys.delete(e.code));
document.addEventListener('mousemove',e=>{if(document.pointerLockElement===canvas){yaw-=e.movementX*.0022;pitch=Math.max(-Math.PI/2+.03,Math.min(Math.PI/2-.03,pitch-e.movementY*.0022))}});document.addEventListener('pointerlockchange',()=>{const active=document.pointerLockElement===canvas;hint.classList.toggle('show',started&&!active);statusLabel.innerHTML=active?'<i></i> EXPLORING':'<i></i> PAUSED'});canvas.addEventListener('click',requestControl);$('#start').addEventListener('click',()=>{if(!loaded)return;started=true;intro.classList.add('hidden');setMode('walk');requestControl()});document.querySelectorAll('.mode').forEach(b=>b.addEventListener('click',()=>{setMode(b.dataset.mode);requestControl()}));$('#reset').addEventListener('click',()=>{resetPosition();requestControl()});playerHeightInput.addEventListener('input',()=>{const value=Number(playerHeightInput.value);if(!Number.isFinite(value)||value<=0)return;const previousEye=getEye();playerHeight=value;if(mode==='walk')camera.position.y+=playerHeight-previousEye});moveSpeedInput.addEventListener('input',()=>{const value=Number(moveSpeedInput.value);if(Number.isFinite(value)&&value>0)moveSpeed=value});flashlightButton.addEventListener('click',toggleFlashlight);
resize();setMode('walk');animate();
